plugin: aws_ec2
regions:
  - "ap-northeast-2"
keyed_groups:
  - key: tags.Name
  - key: tags.task
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address
  ansible_user: "'ec2-user'"
